# Generated by Django 4.0 on 2021-12-15 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('male', 'male'), ('female', 'female'), ('uni', 'uni')], max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='JewelryShape',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shape', models.CharField(choices=[('R', 'Ring'), ('N', 'Necklace'), ('E', 'Earring'), ('B', 'Bracelet')], max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='MetalColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(choices=[('W', 'White Gold'), ('Y', 'Yellow Gold'), ('R', 'Rose Gold'), ('S', 'Silver')], max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='MetalType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('14k', '14k'), ('18k', '18k')], max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='StoneShape',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shape', models.CharField(choices=[('BR', 'Round'), ('PC', 'Princess'), ('CU', 'Cushion'), ('OV', 'Oval'), ('EM', 'Emerald'), ('PS', 'Pear'), ('AC', 'Asscher'), ('RA', 'Radiant'), ('MQ', 'Marquise'), ('O', 'Other')], max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='StoneType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('S', 'Sapphire'), ('R', 'Ruby'), ('E', 'Emerald'), ('D', 'Diamond')], max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Jewelry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('image', models.URLField(max_length=300)),
                ('date', models.DateField(auto_now_add=True)),
                ('gender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.gender')),
                ('jewelryShape', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.jewelryshape')),
                ('metalColor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.metalcolor')),
                ('metalType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.metaltype')),
                ('stoneShape', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.stoneshape')),
                ('stoneType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.stonetype')),
            ],
        ),
    ]
