# Generated by Django 4.0 on 2021-12-16 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jewelryshape',
            name='shape',
            field=models.CharField(choices=[('R', 'Ring'), ('N', 'Necklace'), ('E', 'Earrings'), ('B', 'Bracelet')], max_length=20, unique=True),
        ),
    ]
